### ISSUE TITLE
Naming Convention scripts showing up twice

### ISSUE THREAD

**Issue by kylejacksonb** [stinb/plugins#9]
I don't know if this is related to the merge of the CodeCheck and Plugins repositories, but I did not notice this before the merger.

All my naming convention checks are showing up twice and the duplicates have the same Id:

![image](https://github.com/user-attachments/assets/48daaa5b-a8e7-4166-8761-0da54c1cafd6)

![image](https://github.com/user-attachments/assets/7a19760b-f036-4b9f-8378-b4446a392039)

![image](https://github.com/user-attachments/assets/fa15a82f-fccf-4070-bc5d-133b72072085)

**Comment by nstander** [comment]
@hackhaslam Do you want this one? I think it's because the change moving codecheck into the plugins repository means the plugins folder is now getting scanned twice. So, all the code deciding what's enabled by default and also all the code that prevents the Codecheck directory from being scanned for non-code check list requests is broken.

**Comment by hackhaslam** [comment]
This should be fixed by 2786690aaf64b7f4696b15a687fe67984b308021.

**Comment by kylejacksonb** [comment]
@hackhaslam None of the naming conventions are showing up now.

**Comment by kylejacksonb** [comment]
I am missing A LOT of check now

![image](https://github.com/user-attachments/assets/a5522aad-cbc2-49cd-bc7f-45206724edbf)

**Comment by hackhaslam** [comment]
All codecheck scripts are now enabled by default in stinb/sti@2b7b8c9cb166b1c766b2b21a58b328317c83425c.

**Comment by kylejacksonb** [comment]
I'm still seeing duplicates:

![image](https://github.com/user-attachments/assets/6f9a0eab-ea30-48b9-8e6a-9d4cca2535fc)

**Comment by kylejacksonb** [comment]
Some of the duplicates are gone. Classes, Enumberator and Enums only show up once.

**Comment by hackhaslam** [comment]
I fixed Python scripts in stinb/sti@7f9b6b37514cfa111ce1facd4f74fecee368389f.

**Comment by kylejacksonb** [comment]
Looks good.
